### ISSUE TITLE
set_call in XtBuilder play two roles

### ISSUE THREAD

**Issue by daogangtang** [paritytech/substrate-subxt#10]
Now in set_call, we do two things now:

1. set_call
2. build the XtBuilder instance

Should we split it into two methods: set_call() and build(), and use it as:
```
xt.foo().bar().set_call().build()
```

**Comment by ascjones** [comment]
The idea with this was to instantiate a new builder with `Valid` as the type parameter so that we have access to the `submit` and `submit_and_watch` methods. And it is intended to only be called by the module extensions to the builder.

However I agree this is not clear and could do with some refactoring, at least making that function not public.

**Comment by ascjones** [comment]
Closed by #24
