### ISSUE TITLE
`register_type_size` incorrectly sizes some types

### ISSUE THREAD

**Issue by gregdhill** [paritytech/substrate-subxt#196]
For example:

```rust
enum Hashes {
    H160(H160),
    H256(H256),
}

impl Default for Hashes {
    fn default() -> Self {
        Self::H160(H160::zero())
    }
}
```

See: https://github.com/paritytech/substrate-subxt/blob/master/src/events.rs#L118

Since we only size the default implementation, we are unable to decode larger variants.

**Comment by ascjones** [comment]
You are right, this is a bug. 

A quick fix solution would be to provide a method to register a custom common type as above which implements `Decode`.

However this is not ideal and neither is having to register the type sizes at all. I am currently working on improving the substrate metadata to provide rich type data so that none of this is required. It is still at very early prototype stage though, so wouldn't rely on it if you need something quickly.
