### ISSUE TITLE
Error: MissingTypeSizes(["Claims::Claimed::EthereumAddress"])

### ISSUE THREAD

**Issue by samuelvanderwaal** [paritytech/substrate-subxt#270]
I'm getting a `MissingTypeSizes` error when trying to query a Polkadot node using the `fetch_all_accounts` example code. Does this library work with Polkadot nodes, and if so, is the `DefaultNodeRuntime` the correct type for the ClientBuilder for this case?

```rust
use substrate_subxt::{
    system::AccountStoreExt,
    ClientBuilder,
    DefaultNodeRuntime,
};

#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();

    let client = ClientBuilder::<DefaultNodeRuntime>::new()
        .set_url("ws://meerkat.samuelvanderwaal.com:9944")
        .build().await?;
    let mut iter = client.account_iter(None).await?;
    while let Some((key, account)) = iter.next().await? {
        println!("{:?}: {}", key, account.data.free);
    }
    Ok(())
}
```

**Comment by ascjones** [comment]
We probably need to add a `PolkadotRuntime` with all the required type sizes pre registered. That said you should be able to use `DefaultNodeRuntime` in this example: You can either register the type size for that type using `register_type_size` on the client builder or just `skip_type_sizes_check`. Those are only needed if subscribing to events.

However in the near future we plan to overhaul this library so that it will work with any runtime without any manual type size registration required.

**Comment by samuelvanderwaal** [comment]
Thanks!
